config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  
  root to: 'welcome#home'

  get 'welcome/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :date, :room, :syllabus, :weblink, :week, :time)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @mon_subjects = Subject.where(week: 1).order('time')
    @tue_subjects = Subject.where(week: 2).order('time')
    @wed_subjects = Subject.where(week: 3).order('time')
    @thu_subjects = Subject.where(week: 4).order('time')
    @fri_subjects = Subject.where(week: 5).order('time')
    
    @today_subjects = Subject.where(week: Time.zone.now.wday).order('time')
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#c7000a">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#c7000a">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>GoghSupport</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= render 'application/favicon' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark" style="background-color: #c7000a;">
      <%= link_to 'Gogh Sup', root_path, class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home <span class="sr-only">(current)</span>'.html_safe, root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Moodle', 'https://lms.imc.tut.ac.jp/', class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to '教務システム', 'https://kyomu.office.tut.ac.jp/portal/', class: "nav-link"%>
          </li>
        </ul>
      </div>
    </nav>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :subject_date %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room, id: :subject_room %>
  </div>

  <div class="field">
    <%= form.label :syllabus %>
    <%= form.text_field :syllabus, id: :subject_syllabus %>
  </div>

  <div class="field">
    <%= form.label :weblink %>
    <%= form.text_field :weblink, id: :subject_weblink %>
  </div>

  <div class="field">
    <%= form.label :week %>
    <%= form.number_field :week, id: :subject_week %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.number_field :time, id: :subject_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Room</th>
      <th>Syllabus</th>
      <th>Weblink</th>
      <th>Week</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.date %></td>
        <td><%= subject.room %></td>
        <td><%= subject.syllabus %></td>
        <td><%= subject.weblink %></td>
        <td><%= subject.week %></td>
        <td><%= subject.time %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<div class="pt-3 pb-3">
  <h3><%= @subject.name %></h3>
  <hr>
  <p>
    <strong>Date:</strong>
    <%= @subject.date %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= @subject.room %>
  </p>
</div>

<div class="pt-3 pb-3">
  <h4>関連リンク</h4>
  <hr>

  <% if @subject.syllabus.start_with?("https://") %>
    <p>
      <strong>Syllabus:</strong>
      <%= link_to @subject.syllabus[0..30]+'...', @subject.syllabus %>
    </p>
  <% end %>

  <% if @subject.weblink.start_with?("http") %>
    <p>
      <strong>Weblink:</strong>
      <%= link_to @subject.weblink[0..30]+'...', @subject.weblink %>
    </p>
  <% end %>
</div>

<%= link_to 'Back', root_path %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/home.html.erb
<div class="pt-3">
  <h1>Welcome</h1>
</div>
<div class="pt-3 pb-3">
  <h2>Today</h2>
  <% if @today_subjects.blank? %>
    <div class="alert alert-info p-3" role="alert">
      <h4 class="alert-heading">そうだ、今日は休もう。</h4>
      <p>まあどう過ごすかは人それぞれだけど、楽しく過ごしたいよね。</p>
      <hr>
      <div class="text-right">
        <%= link_to '<button type="button" class="btn btn-info">Twitter</button>'.html_safe, 'https://twitter.com/?lang=ja' %>
        <%= link_to '<button type="button" class="btn btn-outline-info">YouTube</button>'.html_safe, 'https://www.youtube.com/' %>
      </div>
    </div>
  <% else %>
    <table class="table table-striped">
      <tbody>
        <% @today_subjects.each do |subject| %>
          <tr>
            <td><%= link_to subject.name, subject %></td>
            <td><%= subject.date %></td>
            <td><%= subject.room %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<div class="pt-3 pb-3">
  <h2>Timetable</h2>
  <table class="table table-striped">
    <h3>Monday</h3>
    <tbody>
      <% @mon_subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.date %></td>
          <td><%= subject.room %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped">
    <h3>Tuesday</h3>
    <tbody>
      <% @tue_subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.date %></td>
          <td><%= subject.room %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped">
    <h3>Wednesday</h3>
    <tbody>
      <% @wed_subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.date %></td>
          <td><%= subject.room %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped">
    <h3>Thursday</h3>
    <tbody>
      <% @thu_subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.date %></td>
          <td><%= subject.room %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped">
    <h3>Friday</h3>
    <tbody>
      <% @fri_subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, subject %></td>
          <td><%= subject.date %></td>
          <td><%= subject.room %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>